name: Docker Image CI

on:
  schedule:
    - cron: "0 6 1 * *"
  push:
    paths: [ Dockerfile ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3.2.0
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image -- Ubuntu
      run: docker buildx create --use |
            docker buildx build --push \
              --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7 \
              --tag ztangc1/ubuntu-basic:latest \
              --file Dockerfile ./
    - name: Build the Docker image -- Alpine
      run: docker buildx create --use |
            docker buildx build --push \
              --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7 \
              --tag ztangc1/alpine-basic:latest \
              --file alpine.dockerfile ./
